spring.datasource.url=jdbc:postgresql://localhost:5432/db4thefairvalueC2
spring.datasource.username=postgres
spring.datasource.password=ninoharu
# Doma?PostgreSQL???
doma.dialect=postgres
# Hibernate?JDBC?????????????
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.seasar.doma=DEBUG


# DB?PostgreSQL??????????????????????????
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=DEBUG
# Doma?SQL???????????????????
logging.level.org.seasar.doma.jdbc.UtilLoggingJdbcLogger=DEBUG